[workspace]
members = [
  "crates/client/commitment-state-diff",
  "crates/client/db",
  "crates/client/deoxys",
  "crates/client/genesis-data-provider",
  "crates/client/mapping-sync",
  "crates/client/rpc",
  "crates/client/rpc-core",
  "crates/client/settlement",
  "crates/client/storage",
  "crates/node",
  "crates/pallets/starknet",
  "crates/pallets/starknet/runtime_api/",
  "crates/primitives/block",
  "crates/primitives/chain-id",
  "crates/primitives/commitments",
  "crates/primitives/contract",
  "crates/primitives/convert",
  "crates/primitives/digest-log",
  "crates/primitives/fee",
  "crates/primitives/felt",
  "crates/primitives/genesis-config/",
  "crates/primitives/hashers",
  "crates/primitives/messages",
  "crates/primitives/program-hash",
  "crates/primitives/sequencer-address",
  "crates/primitives/snos-output",
  "crates/primitives/state",
  "crates/primitives/storage",
  "crates/primitives/transactions",
  "crates/runtime",
]
resolver = "2"
# All previous except for `starknet-rpc-test` and `starknet-e2e-test`
# We don't want `cargo test` to trigger its tests
default-members = [
  "crates/client/commitment-state-diff",
  "crates/client/db",
  "crates/client/genesis-data-provider",
  "crates/client/mapping-sync",
  "crates/client/rpc",
  "crates/client/rpc-core",
  "crates/client/settlement",
  "crates/client/storage",
  "crates/node",
  "crates/pallets/starknet",
  "crates/pallets/starknet/runtime_api/",
  "crates/primitives/block",
  "crates/primitives/chain-id",
  "crates/primitives/commitments",
  "crates/primitives/digest-log",
  "crates/primitives/fee",
  "crates/primitives/felt",
  "crates/primitives/genesis-config/",
  "crates/primitives/hashers",
  "crates/primitives/messages",
  "crates/primitives/program-hash",
  "crates/primitives/sequencer-address",
  "crates/primitives/state",
  "crates/primitives/storage",
  "crates/primitives/transactions",
  "crates/runtime",
]

[profile.dev]
incremental = true
panic = "abort"

[profile.release]
panic = "unwind"

[profile.production]
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
inherits = "release"
lto = true           # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary

[workspace.package]
authors = ["Antiyro <@antiyro>"]
edition = "2021"
repository = "https://github.com/kasarlabs/deoxys/"
version = "0.1.0"

[workspace.dependencies]
# Substrate frame dependencies
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }

# Substrate primitives dependencies
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-consensus-aura = { git = "http://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-database = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-statement-store = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-storage = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-trie = { version = "22.0.0", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }

# Substrate client dependencies
sc-client-db = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", features = [
  "rocksdb",
] }
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-network-common = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-network-sync = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
# For integration tests in order to create blocks on demand
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-block-builder = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-cli = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-keystore = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-proposer-metrics = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
sc-utils = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }

# Substrate build & tools dependencies
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.10.0-dev", git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }

# Substrate Frame pallet
pallet-aura = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
pallet-grandpa = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }

# Bonsai trie dependencies
bonsai-trie = { default-features = false, git = "https://github.com/antiyro/bonsai-trie.git", branch = "oss" }

# Madara pallets
pallet-starknet = { path = "crates/pallets/starknet", default-features = false }
pallet-starknet-runtime-api = { path = "crates/pallets/starknet/runtime_api", default-features = false }
# Madara primtitives
mp-block = { path = "crates/primitives/block", default-features = false }
mp-chain-id = { path = "crates/primitives/chain-id", default-features = false }
mp-commitments = { path = "crates/primitives/commitments", default-features = false }
mp-contract = { path = "crates/primitives/contract", default-features = false }
mp-convert = { path = "crates/primitives/convert", default-features = false }
mp-digest-log = { path = "crates/primitives/digest-log", default-features = false }
mp-fee = { path = "crates/primitives/fee", default-features = false }
mp-felt = { path = "crates/primitives/felt", default-features = false }
mp-genesis-config = { path = "crates/primitives/genesis-config", default-features = false }
mp-hashers = { path = "crates/primitives/hashers", default-features = false }
mp-messages = { path = "crates/primitives/messages", default-features = false }
mp-program-hash = { path = "crates/primitives/program-hash", default-features = false }
mp-sequencer-address = { path = "crates/primitives/sequencer-address", default-features = false }
mp-simulations = { path = "crates/primitives/simulations", default-features = false }
mp-snos-output = { path = "crates/primitives/snos-output", default-features = false }
mp-state = { path = "crates/primitives/state", default-features = false }
mp-storage = { path = "crates/primitives/storage", default-features = false }
mp-transactions = { path = "crates/primitives/transactions", default-features = false }

# Madara client
mc-commitment-state-diff = { path = "crates/client/commitment-state-diff" }
mc-db = { path = "crates/client/db" }
mc-genesis-data-provider = { path = "crates/client/genesis-data-provider" }
mc-l1-messages = { path = "crates/client/l1-messages" }
mc-mapping-sync = { path = "crates/client/mapping-sync" }
mc-rpc = { path = "crates/client/rpc" }
mc-rpc-core = { path = "crates/client/rpc-core" }
mc-settlement = { path = "crates/client/settlement" }
mc-storage = { path = "crates/client/storage" }

# Madara runtime
madara-runtime = { path = "crates/runtime" }

# Starknet dependencies
# Cairo Virtual Machine
cairo-vm = { git = "https://github.com/keep-starknet-strange/cairo-rs", branch = "no_std-support-21eff70", default-features = false, features = [
  "cairo-1-hints",
  "parity-scale-codec",
] }
# starknet-accounts = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-contract = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-core = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-crypto = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-ff = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-providers = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
# starknet-signers = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }

# temporary fokr fix for `failed deserialization when accessible_scopes is missing`
# until we can update to commit c974e5c is starknet-rs
starknet-accounts = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-contract = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-core = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-crypto = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-ff = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-providers = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-signers = { git = "https://github.com/jbcaron/starknet-rs.git", branch = "classes", default-features = false }
starknet-types-core = { version = "0.0.7", default-features = false }

blockifier = { git = "https://github.com/keep-starknet-strange/blockifier", branch = "no_std-support-7578442", default-features = false, features = [
  "parity-scale-codec",
] }
starknet_api = { git = "https://github.com/keep-starknet-strange/starknet-api", branch = "no_std-support-dc83f05", features = [
  "parity-scale-codec",
  "testing",
], default-features = false }

# Cairo lang
cairo-lang-casm = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }
cairo-lang-casm-contract-class = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }
cairo-lang-starknet = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530" }
cairo-lang-utils = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }

# Ethers: using the same versions as in Anvil
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-solc = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }

# Zaun
starknet-core-contract-client = { git = "https://github.com/keep-starknet-strange/zaun" }
zaun-sandbox = { git = "https://github.com/keep-starknet-strange/zaun", package = "sandbox" }

# Other third party dependencies
anyhow = "1.0.75"
async-trait = "0.1.77"
bitvec = { version = "1", default-features = false }
clap = { version = "4.4.8", default-features = false }
derive_more = { version = "0.99.17", default-features = false }
flate2 = "1.0.28"
futures = { version = "0.3.29", default-features = false }
futures-timer = { version = "3.0.2", default-features = false }
hex = { version = "0.4.3", default-features = false }
indexmap = { git = "https://github.com/bluss/indexmap", rev = "ca5f848e10c31e80aeaad0720d14aa2f6dd6cfb1", default-features = false }
jsonrpsee = { version = "0.16.3", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
linked-hash-map = { version = "0.5.6", default-features = false }
log = { version = "0.4.20", default-features = false }
md5 = { version = "0.7.0", default-features = false }
num-bigint = "0.4.4"
num-traits = "0.2.17"
parity-scale-codec = { version = "3.2.2", default-features = false }
parking_lot = "0.12.1"
phf = { version = "0.11", default-features = false }
pretty_assertions = "1.4.0"
reqwest = { version = "0.11.22", default-features = false }
rstest = "0.18.1"
safe-mix = { version = "1.0", default-features = false }
scale-codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
scale-info = { version = "2.10.0", default-features = false }
serde = { version = "1.0.192", default-features = false }
serde_json = { version = "1.0.108", default-features = false }
serde_with = { version = "2.3.3", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
thiserror = "1.0.50"
thiserror-no-std = "2.0.2"

# Deoxys
assert = "0.0.4"
assert_matches = "1.5.0"
async-lock = "3.1.0"
async-stream = "0.3.3"
axum = "0.6.12"
base64 = "0.13.0"
byteorder = "1.4.3"
camelpaste = "0.1.0"
chrono = "0.4.26"
const_format = "0.2.30"
enum-iterator = "1.4.1"
futures-channel = "0.3.21"
futures-util = "0.3.21"
hashbrown = "0.14.2"
http = "0.2.8"
hyper = "0.14"
insta = "1.29.0"
integer-encoding = "3.0.4"
itertools = "0.12.1"
jsonschema = "0.17.0"
libmdbx = "0.3.5"
mc-deoxys = { path = "crates/client/deoxys" }
metrics = "0.21.0"
mockall = "0.11.2"
mockito = "0.31.0"
once_cell = "1.17.1"
openssl = { version = "0.10", features = ["vendored"] }
os_info = "3.6.0"
paste = "1.0.9"
primitive-types = "0.12.1"
prometheus-parse = "0.2.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.9.0"
rustc-hex = "2.1.0"
schemars = "0.8.12"
serde_yaml = "0.9.16"
simple_logger = "4.0.0"
strum = "0.25.0"
strum_macros = "0.25.2"
subxt = "0.29"
tempfile = "3.3.0"
tokio = "1.34.0"
tokio-retry = "0.3"
tokio-stream = "0.1.8"
tower = "0.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = "2.4.1"
validator = "0.12"

[patch."https://github.com/w3f/ring-vrf"]
bandersnatch_vrfs = { git = "https://github.com/w3f/ring-vrf?rev=3ddc20", version = "0.0.4", rev = "3ddc20" }
