name: madara_runner

services:
  madara:
    image: madara:latest
    container_name: "madara_runner"
    cpu_count: 4
    mem_limit: "16gb"
    ports:
      - "9944"
    environment:
      RPC_API_KEY_FILE: /run/secrets/rpc_api_key
    secrets:
      - rpc_api_key
    volumes:
      - /var/lib/madara:/tmp/madara
      - type: bind
        source: ./madara-runner.sh
        target: /usr/local/bin/runner.sh
        read_only: true
        bind:
          create_host_path: false
    entrypoint:
      - /usr/local/bin/runner.sh

secrets:
  rpc_api_key:
    file: .secrets/rpc_api.secret
