[package]
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
description = "FRAME pallet to execute Starknet contracts."
edition.workspace = true
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
name = "pallet-starknet"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"
version.workspace = true

  [package.metadata.docs.rs]
  targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Madara primitives
mp-block = { workspace = true }
mp-chain-id = { workspace = true }
mp-contract = { workspace = true }
mp-digest-log = { workspace = true }
mp-fee = { workspace = true }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
mp-genesis-config = { workspace = true, default-features = false }
mp-hashers = { workspace = true }
mp-program-hash = { workspace = true }
mp-sequencer-address = { workspace = true, features = ["parity-scale-codec"] }
mp-simulations = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-snos-output = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-state = { workspace = true }
mp-storage = { workspace = true, features = ["parity-scale-codec"] }
mp-transactions = { workspace = true, features = ["scale-info"] }

blockifier = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
  "testing",
] }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }
starknet_api = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }

# Substrate frame
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
# Substrate Client
sc-cli = { workspace = true, optional = true }
# Substrate primitives
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
# Frame pallets

# Other third party dependencies
cairo-lang-casm-contract-class = { workspace = true, optional = true, features = [
  "std",
] }
derive_more = { workspace = true }
hashbrown = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, optional = true, features = [
  "blocking",
  "rustls-tls",
] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
hexlit = "0.5.5"
lazy_static = "1.4.0"
pallet-timestamp = { workspace = true }
pretty_assertions = { workspace = true }
project-root = "0.2.2"
starknet-ff = { workspace = true }
test-case = "3.1.0"

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  # Substrate
  "frame-benchmarking?/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-timestamp/std",
  "sc-cli",
  "scale-info/std",
  "sp-inherents/std",
  "sp-io/std",
  "sp-runtime/std",
  # Starknet
  "blockifier/std",
  "mp-felt/std",
  "mp-genesis-config/std",
  "mp-sequencer-address/std",
  "starknet-crypto/std",
  # Other third party dependencies
  "dep:cairo-lang-casm-contract-class",
  "dep:reqwest",
  "mp-block/std",
  "mp-contract/std",
  "mp-simulations/std",
  "parity-scale-codec/std",
  "starknet-core/std",
]
try-runtime = ["frame-support/try-runtime"]
