[package]
name = "mc-block-hashes"
authors.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "create_hash_tables"
path = "src/bin/create_hash_tables.rs"
required-features = ["create_hash_tables"]

[features]
create_hash_tables = [
  "mc-db",
  "clap",
  "mp-chain-config",
  "mp-convert",
  "tokio",
  "starknet-types-core",
  "itertools",
]
default = ["create_hash_tables"]

[dependencies]
anyhow = { workspace = true }

# create_hash_tables dependencies
clap = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
mc-db = { workspace = true, optional = true }
mp-chain-config = { workspace = true, optional = true }
mp-convert = { workspace = true, optional = true }
starknet-types-core = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["rt-multi-thread"] }

[lints]
workspace = true
