[package]
name = "mc-db"
version.workspace = true
edition.workspace = true
description = "Starknet database backend"
authors = [
  "Timothée Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate crates
parity-db = { version = "0.4.12", optional = true }
parity-scale-codec = { workspace = true, default-features = true, features = [
  "derive",
] }
sc-client-db = { workspace = true, default-features = true }
sp-core = { workspace = true }
sp-database = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

# Madara crates
mp-hashers = { workspace = true }
mp-types = { workspace = true }

# Starknet crates
blockifier = { workspace = true, default-features = false, features = [
  "testing",
] }
bonsai-trie = { workspace = true }
starknet-ff = { workspace = true, default-features = false, features = [
  "alloc",
  "serde",
] }
starknet-types-core = { workspace = true, default-features = false, features = [
  "hash",
  "parity-scale-codec",
] }
starknet_api = { workspace = true, default-features = true, features = [
  "parity-scale-codec",
] }

# Other crates
async-trait = { workspace = true }
bitvec = { workspace = true }
ethers = { workspace = true }
kvdb = "0.13.0"
kvdb-rocksdb = { version = "0.19.0", optional = true }
lazy_static = { workspace = true }
log = { workspace = true, default-features = true }
rayon = { workspace = true }
thiserror = { workspace = true }
uuid = "1.4.1"

[features]
default = ["kvdb-rocksdb", "parity-db"]
