[package]
authors.workspace = true
description = "This crate is responsible to sync data"
edition = "2021"
homepage = "https://github.com/madara-alliance/madara"
license = "MIT"
name = "mc-sync"
publish = false
repository = "https://github.com/madara-alliance/madara"
version = "0.7.0"

[features]
default = []
m = ["dep:rodio"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mc-block-import = { workspace = true }
mc-db = { workspace = true }
#mc-eth = { workspace = true }
mc-metrics = { workspace = true }
mc-telemetry = { workspace = true }
mp-block = { workspace = true }
mp-chain-config = { workspace = true }
mp-class = { workspace = true }
mp-convert = { workspace = true }
mp-receipt = { workspace = true }
mp-state-update = { workspace = true }
mp-transactions = { workspace = true }
mp-utils = { workspace = true }

# Starknet
bonsai-trie = { workspace = true }
starknet-core = { workspace = true }
starknet-providers = { workspace = true }
starknet-types-core = { workspace = true }
starknet_api = { workspace = true }


# Other
anyhow = { workspace = true }
bitvec = { workspace = true }
futures = { workspace = true, default-features = true }
log = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true }
rodio = { version = "0.17", optional = true }
serde_json = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "parking_lot",
  "test-util",
  "signal",
] }
url = { workspace = true }

[dev-dependencies]
# test_utils = { path = "./test_utils" }
