[package]
name = "mp-fee"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet fee related logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
cairo-vm = { workspace = true }
frame-support = { workspace = true }
hashbrown = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
starknet-core = { workspace = true }
starknet_api = { workspace = true }

# Optional dependencies
serde_with = { workspace = true, optional = true }
