[test-groups]
eth-rpc = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(eth_client)'
retries = { backoff = "exponential", count = 5, delay = "10s", max-delay = "60s", jitter = true }
test-group = 'eth-rpc'
