[test-groups]
serial-integration = { max-threads = 1 }

#[[profile.default.overrides]]
#filter = 'package(mc-eth)'
#test-group = 'serial-integration'
#
#[[profile.default.overrides]]
#filter = 'package(mc-e2e-tests)'
#test-group = 'serial-integration'
