[package]
name = "mc-p2p"
authors.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
libp2p.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
unsigned-varint.workspace = true

mc-db.workspace = true
mc-rpc.workspace = true
mp-block.workspace = true
mp-chain-config.workspace = true
mp-convert.workspace = true
mp-utils.workspace = true
p2p_stream.workspace = true

starknet-core.workspace = true
starknet-types-core.workspace = true

[lints]
workspace = true

[build-dependencies]
prost-build.workspace = true
