[package]
name = "mp-malachite"
authors.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]

# Madara
mp-block.workspace = true
mp-proto.workspace = true
mp-transactions.workspace = true

# Starknet
starknet-types-core.workspace = true

# P2P
libp2p.workspace = true
malachite-core-types.workspace = true

# Async
tokio.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]

# Async
loom.workspace = true

# Testing
assert_matches.workspace = true
rstest.workspace = true
