[package]
name = "mc-rpc-core"
version.workspace = true
edition.workspace = true
description = "RPC trait of Starknet"
authors = [
  "Timothée Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { workspace = true }
blockifier = { workspace = true, default-features = true }
cairo-lang-casm-contract-class = { workspace = true }
flate2 = { workspace = true }
jsonrpsee = { workspace = true, features = [
  "server",
  "macros",
], default-features = true }
mp-block = { workspace = true }
mp-digest-log = { workspace = true }
mp-felt = { workspace = true }
mp-transactions = { workspace = true, features = ["serde"] }
num-bigint = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
starknet-core = { workspace = true }
starknet_api = { workspace = true, default-features = true }

[dev-dependencies]
assert_matches = { workspace = true }
