[package]
name = "mp-sync"
description = "Madara primitives for synchronization"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Core dependencies
tokio.workspace = true
tracing.workspace = true

# Madara dependencies
mp-rpc.workspace = true

# Other dependencies
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }


[dev-dependencies]
# Starknet
starknet-types-core = { workspace = true }
