[package]
name = "madara"
version = "0.8.0"
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "madara"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=mold"]

[dependencies]
# Database
rocksdb.workspace = true
librocksdb-sys.workspace = true
bonsai-trie.workspace = true

# Madara proc macros
m-proc-macros.workspace = true

# Madara primtitives
mp-block.workspace = true
mp-convert.workspace = true
mp-transactions.workspace = true
mp-class.workspace = true
mp-gateway.workspace = true
mp-rpc.workspace = true
mp-receipt.workspace = true
mp-state-update.workspace = true
mp-utils.workspace = true
mp-chain-config.workspace = true
mp-oracle.workspace = true

# Madara client
mc-analytics.workspace = true
mc-telemetry.workspace = true
mc-db.workspace = true
mc-exec.workspace = true
mc-rpc.workspace = true
mc-gateway-client.workspace = true
mc-gateway-server.workspace = true
mc-sync.workspace = true
mc-settlement-client.workspace = true
mc-mempool.workspace = true
mc-block-production.workspace = true
mc-devnet.workspace = true
mc-submit-tx.workspace = true

# Starknet dependencies
cairo-vm.workspace = true
starknet-accounts.workspace = true
starknet-contract.workspace = true
starknet-core.workspace = true
starknet-crypto.workspace = true
starknet-providers.workspace = true
starknet-signers.workspace = true
starknet.workspace = true
starknet-types-core.workspace = true

blockifier.workspace = true
starknet_api.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-lang-utils.workspace = true

alloy.workspace = true

# Instrumentation
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
tracing = { workspace = true }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Networking
jsonrpsee.workspace = true
tower.workspace = true
tower-http.workspace = true
governor.workspace = true
hyper = { version = "0.14", features = ["server"] }
hyper-tls.workspace = true
hyper-util.workspace = true
http.workspace = true
http-body-util.workspace = true
ip_network.workspace = true
reqwest.workspace = true
url.workspace = true

# Async
tokio.workspace = true
tokio-util.workspace = true
rayon.workspace = true
futures = { workspace = true, features = ["thread-pool"] }
async-trait.workspace = true

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
bincode.workspace = true

# Numbers
base64.workspace = true
bigdecimal.workspace = true
num-traits.workspace = true
num-bigint.workspace = true
primitive-types.workspace = true
rand.workspace = true
crypto-bigint.workspace = true
zeroize.workspace = true

# Std extensions
lazy_static.workspace = true
once_cell.workspace = true
itertools.workspace = true
bitvec.workspace = true
bytes.workspace = true
derive_more.workspace = true

# Error handling
thiserror.workspace = true
anyhow.workspace = true

# Testing
rstest.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
proptest-state-machine.workspace = true
tempfile.workspace = true
httpmock.workspace = true
mockall.workspace = true
fdlimit.workspace = true
assert_matches.workspace = true

# Macros
indoc.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
paste.workspace = true

# Setup
clap.workspace = true
dotenv.workspace = true
figment = { workspace = true, features = ["toml", "json", "yaml"] }

# Misc
flate2.workspace = true
regex.workspace = true
sha3.workspace = true

[features]
default = []
