name: "Changelog Workflow"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  changelog:
    runs-on: self-hosted
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: "Skip-Changelog,dependencies"
