---
name: Task - Run CLI tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cli_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run cli without arguments
        run: |
          cargo run --bin madara --release &
          MADARA_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          kill $MADARA_PID

      - name: Run cli pointing to a file
        run: |
          cargo run --bin madara --release -- --config-file ./configs/args/config.json &
          MADARA_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          kill $MADARA_PID
