# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Workflow - Pull Request Main

# This workflow orchestrates all checks and tests for pull requests
# It uses reusable workflows to keep the configuration DRY
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

# Use concurrency to prevent multiple workflows running on the same PR
concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  # Update database version for schema changes
  update-db-version:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/task-ci-db-version.yml
    secrets: inherit

  # Run Rust-specific linters
  lint-rust:
    needs: update-db-version
    uses: ./.github/workflows/task-lint-cargo.yml
    secrets: inherit

  # Run linters for code style and quality
  lint-code-style:
    needs: update-db-version
    uses: ./.github/workflows/task-lint-code-style.yml

  # ========================================================================= #
  #                                   MADARA                                  #
  # ========================================================================= #

  # Build Madara binary
  build-madara:
    needs: [lint-rust, lint-code-style]
    uses: ./.github/workflows/task-build-madara.yml
    secrets: inherit

  # Run coverage tests
  test-madara:
    needs: build-madara
    uses: ./.github/workflows/task-coverage-madara.yml
    with:
      madara-binary-hash: ${{ needs.build-madara-cairo.outputs.madara-binary-hash }}
    secrets: inherit

  # Run JavaScript tests against the built binary
  test-js:
    needs: test-madara
    uses: ./.github/workflows/task-test-js.yml
    with:
      madara-binary-hash: ${{ needs.build-madara-cairo.outputs.madara-binary-hash }}

  # Run CLI tests against the built binary
  test-cli:
    needs: test-madara
    uses: ./.github/workflows/task-test-cli.yml
    secrets: inherit

  # ========================================================================= #
  #                                ORCHESTRATOR                               #
  # ========================================================================= #

  # Build Orchestrator binary
  build-orchestrator:
    needs: [lint-rust, lint-code-style]
    uses: ./.github/workflows/task-build-orchestrator.yml
    secrets: inherit

  # Run coverage tests
  test-orchestrator:
    needs: [build-madara, build-orchestrator]
    uses: ./.github/workflows/task-coverage-orchestrator.yml
    with:
      madara-binary-hash: ${{ needs.build-madara-cairo.outputs.madara-binary-hash }}
    secrets: inherit

  # Run e2e tests
  test-e2e:
    needs: test-orchestrator
    uses: ./.github/workflows/task-test-orchestrator-e2e.yml
    with:
      madara-binary-hash: ${{ needs.build-madara-cairo.outputs.madara-binary-hash }}
    secrets: inherit

  # ========================================================================= #
  #                                BOOTSTRAPPER                               #
  # ========================================================================= #

  # Build Bootstrapper binary
  build-bootstrapper:
    needs: [lint-rust, lint-code-style]
    uses: ./.github/workflows/task-build-bootstrapper.yml
    secrets: inherit

  # Run coverage tests
  test-bootstrapper:
    needs: [build-madara, build-bootstrapper]
    uses: ./.github/workflows/task-coverage-bootstrapper.yml
    with:
      madara-binary-hash: ${{ needs.build-madara-cairo.outputs.madara-binary-hash }}
    secrets: inherit

  # ========================================================================= #
  #                                MERGE QUEUE                                #
  # ========================================================================= #

  build-nightly:
    uses: ./.github/workflows/task-do-nothing-build-nightly.yml

  # test-hive:
  #   uses: ./.github/workflows/task-do-nothing-test-hive.yml

  publish-nightly:
    uses: ./.github/workflows/task-do-nothing-publish-nightly.yml
