name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: tag (ex. v0.8.0) to generate release note from
        required: true
      previous:
        description: previous tag (ex. v0.7.0) to generate release note from

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref_name }}

      - name: Generate CHANGELOG body
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.event.inputs.tag || github.ref_name }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_ACTION }}
          tag: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
