---
name: Task - Run check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: actions/cache@v3
        with:
          path: |
            target/release/deoxys
          key:
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Setup rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: rustup show

      - name: Setup check deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler libasound2-dev

      - name: Check the project
        run: |
          cargo check --release --workspace
