---
name: Task - Security Audit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  security_audit:
    name: Security audit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
