name: Starknet-js Compatibility Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  js-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            target/release/madara
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          fail-on-cache-miss: true
      - name: Setup dev chain
        run: |
          ls -la
          pwd
          ./target/release/madara -- --name madara --base-path ../madara-db --network devnet --authority --telemetry-disabled --rpc-port 9944 --rpc-cors "*" --rpc-external --devnet --preset test
      - name: Run starknet-js test
        run: |-
          MADARA_RUN_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          cd js_tests
          npm install
          node main.js
          kill $MADARA_RUN_PID
