# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build Orchestrator

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-binaries:
    permissions:
      pull-requests: write
    runs-on: karnot-arc-runner-set

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          cache-key: orchestrator

      # Check Orchestrator
      - name: Cargo build
        run: |
          export GIT_COMMIT_HASH=$GITHUB_SHA
          cargo check -p orchestrator --release
