name: Task - Lint Cargo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}

      - name: Cargo fmt
        run: |
          cargo fmt -- --check
          cargo fmt --tests -- --check

      - name: Cargo Clippy
        run: |
          cargo clippy --workspace --no-deps -- -D warnings
          cargo clippy --workspace --tests --no-deps -- -D warnings
