# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build Orchestrator

# This workflow builds the main Madara binary and related components
# It also caches the build artifacts for other workflows to use
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      orchestrator-binary-hash:
        description: "Hash of the built orchestror binary"
        value: ${{ jobs.build-binaries.outputs.orchestrator-binary-hash }}

jobs:
  build-binaries:
    permissions:
      pull-requests: write
    runs-on: karnot-arc-runner-set
    outputs:
      orchestrator-binary-hash: ${{ steps.generate-binary-hash.outputs.orchestrator-hash }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}

      # Build Orchestrator
      - name: Cargo build
        run: |
          export GIT_COMMIT_HASH=$GITHUB_SHA
          cargo build -p orchestrator --release

      # Generate hash for the Orchestrator binary
      - name: Generate binary hashes
        id: generate-binary-hash
        run: |
          # Get current Unix timestamp for uniqueness
          TIMESTAMP=$(date +%s)

          # Path to the compiled Orchestrator binary
          BINARY_PATH=./target/release/orchestrator
          HASH=$(echo "$TIMESTAMP" | cat - $BINARY_PATH | sha256sum | awk '{ print $1 }')
          echo "orchestrator-hash=$HASH" >> $GITHUB_OUTPUT
          echo "Hash of the orchestrator is: $HASH (with timestamp: $TIMESTAMP)"

      # Upload Orchestrator binary as artifact
      - name: Upload Orchestrator binary
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-binary-${{ steps.generate-binary-hash.outputs.orchestrator-hash }}
          path: target/release/orchestrator
