# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build Madara

# This workflow builds the main Madara binary and related components
# It also caches the build artifacts for other workflows to use
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      madara-binary-hash:
        description: "Hash of the built madara binary"
        value: ${{ jobs.build-binaries.outputs.madara-binary-hash }}

jobs:
  build-binaries:
    permissions:
      pull-requests: write
    runs-on: karnot-arc-runner-set
    outputs:
      madara-binary-hash: ${{ steps.generate-binary-hash.outputs.madara-hash }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load env
        uses: ./.github/actions/load-env

      - name: Rust setup
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          cache-key: madara

      - name: Debug
        run: |
          ls -la
          cat .cargo/config.toml

      # Build Madara
      - name: Cargo build
        run: |
          export GIT_COMMIT_HASH=$GITHUB_SHA
          cargo build -p madara --release

      # Generate hash for the Madara binary
      - name: Generate binary hashes
        id: generate-binary-hash
        run: |
          # Get current Unix timestamp for uniqueness
          TIMESTAMP=$(date +%s)

          # Path to the compiled Madara binary
          BINARY_PATH=./target/release/madara
          HASH=$(echo "$TIMESTAMP" | cat - $BINARY_PATH | sha256sum | awk '{ print $1 }')
          echo "madara-hash=$HASH" >> $GITHUB_OUTPUT
          echo "Hash of the madara is: $HASH (with timestamp: $TIMESTAMP)"

      # Upload Madara binary as artifact
      - name: Upload Madara binary
        uses: actions/upload-artifact@v4
        with:
          name: madara-binary-${{ steps.generate-binary-hash.outputs.madara-hash }}
          path: target/release/madara
